baseURL = 'https://oustandinginstructions.com/'
languageCode = 'en-US'
title = 'Outstanding Instructions'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20

#  [[menus.main]]
#    name = 'Tags'
#    pageRef = '/tags'
#    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
